<?php
$_code = $this->getMethodCode();

$installment        = Mage::getStoreConfig('payment/payfull/use_installment');
$secure_3d          = Mage::getStoreConfig('payment/payfull/use3d_secure');
$quote              = Mage::getModel('checkout/session')->getQuote();
$quoteData          = $quote->getData();
$grandTotal         = $this->getTotal();
$currency_symbol    = $this->getCurrencySymbole();
$secure_3d          = 1;

$payfullHelpImagesPath = $this->getSkinUrl('images/payfull/');
if(strpos($payfullHelpImagesPath, 'rwd') === false){
    $payfullHelpImagesPath = str_replace('frontend/base', 'frontend/rwd', $payfullHelpImagesPath);
}
?>
<style>
    .input-cc-number-visa {
        background: rgba(0, 0, 0, 0) url("<?php echo $payfullHelpImagesPath.'payfull_creditcard_visa.png'; ?>") no-repeat scroll right center / 13% auto !important;
        float: left;
    }

    .input-cc-number-master {
        background: rgba(0, 0, 0, 0) url("<?php echo $payfullHelpImagesPath.'payfull_creditcard_master.png'; ?>") no-repeat scroll right center / 13% auto !important;
        float: left;
    }

    .input-cc-number-not-supported {
        background: rgba(0, 0, 0, 0) url("<?php echo $payfullHelpImagesPath.'payfull_creditcard_not_supported.png'; ?>") no-repeat scroll right center / 4% auto !important;
        float: left;
    }

    #payment_form_payfull > li {width: 75% !important;  }
    #payment_form_payfull input[type='text'] {width: 100% !important;  }
    #payment_form_payfull .v-fix {width: 100% !important;  }
    #payment_form_payfull .divSelectMenu {width: 49% !important;  }
    #payment_form_payfull .divSelectMenu > select {width: 100% !important; height: 30px !important; }
    .card_loder > img {display: inline;vertical-align: middle;width: 25px;}
    .card_image > img {display: inline-block;width: auto;height:25px;vertical-align: middle;}
    .card_image { display: inline-block;  padding:0 5px;vertical-align: bottom;}
    .toatl_label h3 {margin: 15px 0 0 0;}
    .install_body_label {float: left;width: 30%;height: 40px;text-align: center; border-bottom: 1px solid #d2d2d2;line-height: 40px;}
    .installment_row {/* padding-top: 10px;*/}
    .install_body_label.installment_radio, .installmet_head .install_head_label.add_space {height: 40px;text-align: center;width: 10%;line-height: 40px;}
    #installment_table_id {background-color: #eee;border: 1px solid;border-radius: 5px;padding: 10px;margin-top: 20px;}
    .installmet_head .install_head_label {float: left;font-weight: bold;text-align: center;width: 30%; height: 40px;line-height: 40px;border-bottom: 2px solid #d2d2d2; }
    .installment_body , .installment_footer {  clear: both; }
    .toatl_label {display:  none;}
    .use3d_secure_class {float:  left;}
    .full-width { width: 100% !important;}
    #enable3dsecure label {  margin-top: 10px;}
    #payfull_use3d_secure {  margin-top: 10px; margin-right: 10px;}
</style>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li class="toatl_label">
        <h3>        
            <label><b><?php echo $this->__('Total: ') ?></b></label>
            <span rel="<?php echo $grandTotal; ?>" id="grand_total" class="grant_total_custom"><?php echo Mage::helper('core')->currency($grandTotal, true, false); ?></span>
        </h3>
    </li>
    <li>
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box full-width">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->escapeHtml($this->getInfoData('cc_owner')) ?>" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box full-width">
            <input value="" type="text" pattern="\d*" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-cc-number-not-supported  input-text required-entry validate-cc-number validate-cc-type" maxlength="16"  />
            <span style="display: none;" class="card_loder" id="payfull_card_load">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif'); ?>" />
            </span>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box full-width">
            <div class="v-fix divSelectMenu">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k => $v): ?>
                        <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
					<?php endforeach ?>
                </select>
            </div>
            <div class="v-fix divSelectMenu">
                    <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                    <?php foreach ($this->getCcYears() as $k => $v): ?>
                        <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
					<?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php if ($this->hasVerification()): ?>
    <li>
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box full-width">
            <div class="v-fix">
                <input type="text" pattern="\d*" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
    <?php endif; ?>
    <?php  if ($installment == 1) : ?>
    <li>
        <div id="installment_table_id" class="full-width">
            <div class="installmet_head">
                <div class="install_head_label add_space"><img style="display: none" class="bank_photo" data-src="<?php echo $payfullHelpImagesPath; ?>" src=""></div>
                <div class="install_head_label"><?php echo $this->__('Installmet') ?></div>
                <div class="install_head_label"><?php echo $this->__('Amount / Month') ?></div>
                <div class="install_head_label"><?php echo $this->__('Total') ?></div>
            </div>
            <div class="installment_body" id="installment_body">
                <div class="installment_row">
                    <div class="install_body_label installment_radio"><input rel="1" type="radio" class="installment_radio" checked name="payment[installment]" value="1" /></div>
                    <div class="install_body_label installment_lable_code">1</div>
                    <div class="install_body_label"><?php echo Mage::helper('core')->currency($grandTotal, true, false); ?></div>
                    <div class="install_body_label final_commi_price" rel="<?php echo $grandTotal; ?>"><?php echo Mage::helper('core')->currency($grandTotal, true, false); ?></div>
                </div>
            </div>
            <div class="installment_footer"></div>
        </div>
        <input id="<?php echo $_code ?>_has3d" type="hidden" title="<?php echo $this->__('Has 3D') ?>" name="payment[has3d]" value="<?php echo $this->htmlEscape($this->getInfoData('has3d')) ?>" />
        <input id="<?php echo $_code ?>_bank_id" type="hidden" title="<?php echo $this->__('Bank') ?>" name="payment[bank_id]" value="<?php echo $this->htmlEscape($this->getInfoData('bank_id')) ?>" />
        <input id="<?php echo $_code ?>_gateway" type="hidden" title="<?php echo $this->__('Gateway') ?>" name="payment[gateway]" value="<?php echo $this->htmlEscape($this->getInfoData('gateway')) ?>" />
    </li>
    <?php endif; ?>

    <?php if ($secure_3d == 1) : ?>
        <li class="td_secure" id="enable3dsecure">
            <div class="input-box full-width">
                <input class="use3d_secure_class" type="checkbox" id="<?php echo $_code ?>_use3d_secure" value="1" name="payment[use3d_secure]" />
                <label for="<?php echo $_code ?>_use3d_secure"> <?php echo $this->__('Use 3D secure Payments System') ?></label>
            </div>
        </li>
    <?php endif; ?>

</ul>

<script type="text/javascript">

    banks                   = false;
    var grandTotal          = document.getElementById('grand_total').getAttribute('rel');
    var currency_symbole    = '<?php echo $currency_symbol; ?>';
    var $cc                 = document.getElementById('<?php echo $_code ?>_cc_number');
    var $bank               = document.getElementById('<?php echo $_code ?>_bank_id');
    var $has3d              = document.getElementById('<?php echo $_code ?>_has3d');
    var $gateway            = document.getElementById('<?php echo $_code ?>_gateway');
    var $options            = document.getElementById('installment_body');
    var $card_load          = document.getElementById('payfull_card_load');
    var $bank_photo         = document.getElementsByClassName('bank_photo')[0];
    var $enable3dSecure     = document.getElementById('enable3dsecure');
    BIN_GLOBAL_FOR_CARD     = '00000';
    INSTALMENTS_RESET       = true;
    BIN                     = false;

    $cc.addEventListener('keyup', getCardBrandAndInstallmentsList, false);
    $cc.addEventListener('change', getCardBrandAndInstallmentsList, false);

    function getCardBrandAndInstallmentsList(e){
        var target = e.target || e.srcElement;
        BIN        = target.value;
        BIN = BIN.replace(/ /g,'');
        cardBrandDetector(BIN);

        if(BIN.length > 5) {
            BIN = this.value.substr(0, 6);
            if(BIN == BIN_GLOBAL_FOR_CARD){
                return;
            }else{
                BIN_GLOBAL_FOR_CARD = BIN;
                INSTALMENTS_RESET   = true;
            }


            var url = '<?php echo Mage::getUrl('payfull/service/issuer', array('_secure' => false)); ?>'+'?bin='+BIN;
            $card_load.style.display = 'block';

            var xmlhttp = new XMLHttpRequest();
            xmlhttp.open("GET", url, true);
            xmlhttp.setRequestHeader("X-Requested-With", "XMLHttpRequest");
            xmlhttp.setRequestHeader("X_REQUESTED_WITH", "XMLHttpRequest");
            xmlhttp.send();

            xmlhttp.onreadystatechange = function() {
                if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
                    var response = JSON.parse(xmlhttp.responseText);
                    if(response.data.bank_id != ''){
                        var bankImageSrc = $bank_photo.getAttribute('data-src');
                        if(response.data.type == 'CREDIT'){
                            bankImageSrc = bankImageSrc+'networks/'+response.data.bank_id+'.png';
                        }else{
                            bankImageSrc = bankImageSrc+'banks/'+response.data.bank_id+'.png';
                        }
                        $bank_photo.setAttribute('src', bankImageSrc);
                        $bank_photo.style.display = 'block';
                    }
                    refreshInstallmentsTable(response.data.bank_id, response.data.type);
                    $card_load.style.display = 'none';
                }
            };
        }else{
            BIN_GLOBAL_FOR_CARD = BIN;
            if(INSTALMENTS_RESET){
                INSTALMENTS_RESET = false;
                refreshInstallmentsTable('', '');
            }
            $card_load.style.display  = 'none';
            $bank_photo.style.display = 'none';
        }
    }

    function refreshInstallmentsTable(bankName, cardType){
        buildInstallmentsTable(bankName, cardType);
    }

    function buildInstallmentsTable(bankName, cardType) {
        $options.innerHTML     = '';
        $options.insertAdjacentHTML('beforeend', getInstallementOption(1, grandTotal, '0'));

        var url = '<?php echo Mage::getUrl('payfull/service/banks', array('_secure' => false)); ?>'+'?bin='+BIN;
        $card_load.style.display = 'block';
        var xmlhttp = new XMLHttpRequest();
        xmlhttp.open("GET", url, true);
        xmlhttp.setRequestHeader("X-Requested-With", "XMLHttpRequest");
        xmlhttp.send();
        xmlhttp.onreadystatechange = function() {
            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
                var response = JSON.parse(xmlhttp.responseText);
                banks        = response.data;
                if(cardType != 'CREDIT') return;

                for (var i in banks) {
                    var bank = banks[i];
                    if (bank.bank == bankName) {
                        $bank.value    = bank.bank;
                        $has3d.value   = bank.has3d;
                        $gateway.value = bank.gateway;
                        for (item of bank.installments) {
                            $options.insertAdjacentHTML('beforeend', getInstallementOption(parseInt(item.count), grandTotal, item.commission));
                        }
                        break;
                    }
                }
                $card_load.style.display = 'none';
                createEventListenerToInstallment();
            }
        };
    }

    function getInstallementOption(count, amount, percentage) {
        var commession = percentage.replace('%', '');
        var total = parseFloat(amount) * (1 + parseFloat(commession) / 100);
        var pmon = total / count;
        var checked = count==1 ? 'checked' : '';
        return ''
            + '<div class="installment_row">'
            + '<div class="install_body_label installment_radio">'
            + '<input rel="'+count+'" class="custom_field_installment_radio" type="radio" '+checked+' name="payment[installment]" value="'+count+'" />'
            + '</div>'
            + '<div class="install_body_label installment_lable_code">'+count+'</div>'
            + '<div class="install_body_label"> '+currency_symbole+ pmon.toFixed(2) + '</div>'
            + '<div rel="' + total + '" class="install_body_label final_commi_price"> ' + currency_symbole + parseFloat(total).toFixed(2) + '</div>'
            + '</div>'
            ;
    }

    function cardBrandDetector(number) {
        removeClassFromElement($cc, 'input-cc-number-not-supported');
        var re_visa = new RegExp("^4");
        var re_master = new RegExp("^5[1-5]");
        if (number.match(re_visa) != null){
            addClassToElement($cc, 'input-cc-number-visa');
            removeClassFromElement($cc, 'input-cc-number-master');
        }else if (number.match(re_master) != null){
            addClassToElement($cc, 'input-cc-number-master');
            removeClassFromElement($cc, 'input-cc-number-visa');
        }else{
            addClassToElement($cc, 'input-cc-number-not-supported');
            removeClassFromElement($cc, 'input-cc-number-visa');
            removeClassFromElement($cc, 'input-cc-number-master');
        }
    }

    function addClassToElement(element, className) {
        element.className += ' '+className;
    }

    function removeClassFromElement(element, className) {
        var currentClasses = element.className;
        element.className = currentClasses.replace(className, "");
    }

    function createEventListenerToInstallment(){
        var $installmentRadio = document.getElementsByClassName('custom_field_installment_radio');
        for (var i = 0; i < $installmentRadio.length; i++) {
            $installmentRadio[i].addEventListener('click', showHide3D, false);
        }
    }

    function showHide3D(e) {
        var target = e.target || e.srcElement;
        var count = target.getAttribute('rel');
        var has3D = parseInt($has3d.value);

        if(count!=1 && has3D!=1) {
            $enable3dSecure.style.display = 'none';
            $has3d.checked = false;
        } else {
            $enable3dSecure.style.display = 'block';
        }
    }


</script>